### ISSUE TITLE
Install via Coursier fails

### ISSUE THREAD

**Issue by sideeffffect** [oyvindberg/bleep#178]
```
cs install --channel https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json bleep
https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json
  No modified time in response
Exception in thread "main" java.lang.Exception: Error decoding /home/ondra/.cache/coursier/v1/https/raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json (https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json): Expected object: CursorHistory(List(El(CursorOpDownField(repositories),true)))
        at coursier.install.Channels.$anonfun$find$25(Channels.scala:185)
```
```
cs install --channel https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json /
https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json
  No modified time in response
https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json
  100.0% [##########] 1.3 KiB (37.7 KiB / s)
Exception in thread "main" java.lang.Exception: Error decoding /home/ondra/.cache/coursier/v1/https/raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json (https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json): Expected object: CursorHistory(List(El(CursorOpDownField(repositories),true)))
	at coursier.install.Channels.$anonfun$find$25(Channels.scala:185)
```
```
cs install --channel https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json .
https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json
  No modified time in response
Exception in thread "main" java.lang.Exception: Error decoding /home/ondra/.cache/coursier/v1/https/raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json (https://raw.githubusercontent.com/oyvindberg/bleep/master/channel/bleep.json): Expected object: CursorHistory(List(El(CursorOpDownField(repositories),true)))
        at coursier.install.Channels.$anonfun$find$25(Channels.scala:185)
```
```
cs install --channel https://raw.githubusercontent.com/oyvindberg/bleep/master/channel bleep
https://raw.githubusercontent.com/oyvindberg/bleep/master/channel
  No modified time in response
Exception in thread "main" java.io.FileNotFoundException: /home/ondra/.cache/coursier/v1/https/raw.githubusercontent.com/oyvindberg/bleep/master/channel (Is a directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
```

**Comment by oyvindberg** [comment]
Yeah, i haven't figured out how to do that actually. We could file an issue with coursier and ask how to do it. For GitHub actions this works with a local path as is, but that requires you to clone the repo first.

That said, once the first non-milestone is out I'll add it to the coursier/apps repo so we won't need the channel stuff at all

**Comment by sideeffffect** [comment]
Looking at

https://get-coursier.io/docs/cli-appdescriptors#create-your-own-channel

https://get-coursier.io/docs/cli-appdescriptors#url-based-channels

it seems like you're missing a wrapping `{ "bleep": ... }` around the whole thing in `bleep.json`.
