### ISSUE TITLE
Tests task not working in js / native 

### ISSUE THREAD

**Issue by Baccata** [oyvindberg/bleep#233]
Using : 

* Bleep version 0.0.1-M22
* Macos Monterey 12.3.1
* openjdk version "17.0.3" 2022-04-19

#### Repro setup 

in a temp folder (I need to tweak the template after generation) 

``` 
> bleep build new -p jvm -p js -p native foobar
> rm -r tests 
> mv foobar-test tests
``` 

Then I remove the managed `jvm` because I get an error when unzipping the graal artifact referenced in the default template.

#### JS 

```
> bleep test tests@js3
📗 bootstrapped in 73 ms [t => 119 ms]
📙 You build uses the default system JVM, which can change outside the build. for stable builds over time, let bleep manage your chosen JVM by adding it to bleep.yaml [t => 164 ms]
📗 BSP: Generated JavaScript file '/private/tmp/foobar/.bleep/.bloop/tests/js3/tests@js3.js' [t => 3306 ms]
```

Bleep just stays stuck there. 

#### Native 

``` 
> bleep test tests@native3
📗 bootstrapped in 73 ms [t => 120 ms]
📙 You build uses the default system JVM, which can change outside the build. for stable builds over time, let bleep manage your chosen JVM by adding it to bleep.yaml [t => 166 ms]
📗 BSP: Detecting test frameworks in Scala Native projects is not yet supported [t => 1092 ms]
📗 BSP: Missing configured test frameworks in tests@native3 [t => 1092 ms]
📗 BSP: =============================================== [t => 1092 ms]
📗 BSP: Total duration: 0ms [t => 1092 ms]
📗 BSP: No test suites were run. [t => 1092 ms]
📗 BSP: =============================================== [t => 1092 ms]
📕 tests tests@native3 failed status code ERROR [t => 1111 ms]
```

Trying to set a testFramework explicitly in the build (under `template-native`) doesn't change the error.

**Comment by Baccata** [comment]
Also, forgot to say : thank you for your hard work on this. As a maintainer of heavily-cross-built libraries, I'm quite excited for bleep.

**Comment by oyvindberg** [comment]
Thank you for testing early!

Yeah, I've seen this, but haven't had the time to debug it properly. I'll link in #13 and #14

**Comment by oyvindberg** [comment]
@Baccata re this:
> Then I remove the managed jvm because I get an error when unzipping the graal artifact referenced in the default template.

can you reproduce that? that should not happen

**Comment by Baccata** [comment]
> can you reproduce that? that should not happen 

Yeah I can reproduce with 

``` 
jvm:
  name: graalvm-java17:22.2.0
```

but the unzipping works fine 

``` 
jvm:
  name: graalvm-java17:22.3.0
```

However, with that one I get 

```
📗 bootstrapped in 70 ms [t => 116 ms]
📗 bloop-rifle: Starting compilation server [t => 203 ms]
📕 command failed [t => 605 ms]scala.build.blooprifle.FailedToStartServerException: Server didn't start
        at scala.build.blooprifle.internal.Operations$.$anonfun$startServer$8(Operations.scala:240)
        at scala.build.blooprifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:13)
        at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

(switching from graal to temurin makes it work though)

**Comment by oyvindberg** [comment]
I had seen the failures to run js and native tests, it's one of the blockers for the first "proper" release.

I'm more knowledgeable about Scala.js, so I'll start there.

It was easy to reproduce - the steps you gave did the same on my computer. 

What was more curious though was that i created an sbt build, ran `bloopInstall`, and observed the same behaviour with a fresh sbt and bloop - no bleep involved. This is likely bug(s) in bloop somewhere. Will dig into this going forward

**Comment by oyvindberg** [comment]
```
bloop test foobar-test --verbose
[D] Detected connected cli clients, starting CLI with unique dirs...
[D] Loading 1 projects from '/Users/oyvind/test2/.bloop'...
[D] Loading project from '/Users/oyvind/test2/.bloop/foobar-test.json'
[D] Preparing compilation of foobar-test transitively
[D] Computing sources and classpath hashes for foobar
[D] Scheduling compilation for foobar...
[D] Using successful result for foobar associated with /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-uo_Ev44vQOukePAJPefgqQ==
[D] Cache hit true for plugin /Users/oyvind/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.10/1.8.0/scalajs-compiler_2.13.10-1.8.0.jar
[D] External classes directory /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Read-only classes directory /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-uo_Ev44vQOukePAJPefgqQ==
[D] New rw classes directory /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==-jYO_klpCRkyI6XYqW6lAFA==
[D] No changes
[D] Triggering background tasks for /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Recording new last successful request for foobar associated with /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-uo_Ev44vQOukePAJPefgqQ==
[D] Updating external classes dir with read only /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Computing sources and classpath hashes for foobar-test
[D] Finished copying classes from /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-uo_Ev44vQOukePAJPefgqQ== to /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Scheduling compilation for foobar-test...
[D] Using successful result for foobar-test associated with /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/test-classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-U20tJ8UHRxKqTL7acfEAOw==
[D] Cache hit true for plugin /Users/oyvind/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.10/1.8.0/scalajs-compiler_2.13.10-1.8.0.jar
[D] External classes directory /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/test-classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Read-only classes directory /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/test-classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-U20tJ8UHRxKqTL7acfEAOw==
[D] New rw classes directory /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/test-classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==-QkPva0vOS8GY8siL-sNQPA==
[D] No changes
[D] Triggering background tasks for /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/test-classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Recording new last successful request for foobar-test associated with /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/test-classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-U20tJ8UHRxKqTL7acfEAOw==
[D] Updating external classes dir with read only /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/test-classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Skipping delete of /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-uo_Ev44vQOukePAJPefgqQ== associated with no-op result
[D] Finished copying classes from /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/test-classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-U20tJ8UHRxKqTL7acfEAOw== to /Users/oyvind/test2/.bloop/foobar/bloop-bsp-clients-classes/test-classes-bloop-cli-d1cxKlZZTRiLJeH1B1Hn6Q==
[D] Skipping delete of /Users/oyvind/test2/.bloop/foobar/bloop-internal-classes/test-classes-bloop-cli--5ZdRu1FRX-gLk61WhhoXQ==-U20tJ8UHRxKqTL7acfEAOw== associated with no-op result
[D] Preparing test execution for foobar-test
[D] Setting up test module initializers for foobar-test
[D] Linker: Compute reachability: 151262 us
[D] Linker: Assemble LinkedClasses: 20704 us
[D] Linker: 185017 us
[D] Optimizer: Batch mode: false
[D] Optimizer: Incremental part: 49238 us
[D] Optimizer: Optimizing 381 methods.
[D] Optimizer: Optimizer part: 224377 us
[D] Optimizer: 277533 us
[D] Refiner: Compute reachability: 69684 us
[D] Refiner: Assemble LinkedClasses: 3858 us
[D] Refiner: 76869 us
[D] Module Splitter: Calculate Dependency Info: 293 us
[D] Module Splitter: Analyze Modules: 48 us
[D] Module Splitter: Assemble Modules: 655 us
[D] Module Splitter: 1045 us
[D] Emitter: Generate Classes: 54391 us
[D] Emitter: Write trees: 1568 us
[D] Emitter: Class tree cache stats: reused: 1266 -- invalidated: 0
[D] Emitter: Method tree cache stats: reused: 5869 -- invalidated: 280
[D] Emitter: 64415 us
[D] BasicBackend: Write result: 59154 us
Generated JavaScript file '/Users/oyvind/test2/.bloop/foobar/foobar-test.js'
[D] Resolving test frameworks: List(List(org.scalatest.tools.Framework, org.scalatest.tools.ScalaTestFramework))
[D] Node.js module path: /Users/oyvind/test2/foobar/node_modules
[D] Starting process node...
[D] Current working directory: Some(/Users/oyvind/test2/foobar)
[D] Current environment: Map(SHELL -> /bin/bash, LOGNAME -> oyvind, NVM_BIN -> /Users/oyvind/.nvm/versions/node/v18.9.0/bin, PATH -> /Users/oyvind/bleep:/Users/oyvind/.cargo/bin:/Users/oyvind/.nvm/versions/node/v18.9.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/oyvind/Library/Application Support/Coursier/bin:/Users/oyvind/Library/Application Support/JetBrains/Toolbox/scripts:/opt/homebrew/opt/python@3.10/libexec/bin, NAILGUN_FILESEPARATOR -> /, TERM -> xterm-256color, NVM_CD_FLAGS -> , NAILGUN_TTY_2 -> 0, XPC_SERVICE_NAME -> 0, TERM_PROGRAM -> Apple_Terminal, HOMEBREW_REPOSITORY -> /opt/homebrew, HOMEBREW_CELLAR -> /opt/homebrew/Cellar, JAVA_HOME -> /Users/oyvind/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-darwin-aarch64-22.2.0.tar.gz/graalvm-ce-java17-22.2.0/Contents/Home, BASH_SILENCE_DEPRECATION_WARNING -> 1, NAILGUN_TTY_1 -> 0, HOME -> /Users/oyvind, HOMEBREW_PREFIX -> /opt/homebrew, INFOPATH -> /opt/homebrew/share/info:, NVM_DIR -> /Users/oyvind/.nvm, EDITOR -> nano, USER -> oyvind, MANPATH -> /Users/oyvind/.nvm/versions/node/v18.9.0/share/man:/opt/homebrew/share/man:, __CF_USER_TEXT_ENCODING -> 0x1F5:0x0:0x0, NAILGUN_TTY_0 -> 0, XPC_FLAGS -> 0x0, TMPDIR -> /var/folders/97/g55lxlws47vddz1zwbc7r2qh0000gn/T/, TERM_SESSION_ID -> 9E3DA81C-7543-4EF8-B3DD-A422C534BC90, SHLVL -> 1, _ -> /Users/oyvind/Library/Application Support/Coursier/bin/bloop, TERM_PROGRAM_VERSION -> 447, PWD -> /Users/oyvind/test2, LC_CTYPE -> UTF-8, NAILGUN_PATHSEPARATOR -> :, NODE_PATH -> /Users/oyvind/test2/foobar/node_modules, SSH_AUTH_SOCK -> /private/tmp/com.apple.launchd.5BY6e8LRdu/Listeners, NVM_INC -> /Users/oyvind/.nvm/versions/node/v18.9.0/include/node, __CFBundleIdentifier -> com.apple.Terminal)
```
