### ISSUE TITLE
[BUG] Issue starting metals in neovim/vscode

### ISSUE THREAD

**Issue by KristianAN** [oyvindberg/bleep#378]
Hi. I'm having some problems getting bleep to work with metals in Neovim.

You can see the original error here: https://github.com/scalameta/nvim-metals/issues/669

I tried to update the reflect-config.json as such: https://github.com/oyvindberg/bleep/commit/18eadeec67a79e568631f7feee4d6984669ece96.

This does solve the original error posted on nvim-metals, however now I get this new error.
```shell
      6 6.02 21:06:31 INFO  BSP server: 📕 Shutting down Bleep after encountering fatal error within bloop bsp server, method: buildTargetDependenc│21:06:35 │imetals:ms11se(0%)encyModulesP   │
      5 [                                                                                                                                          │21:06:35 │ metals:  31s (0%)               │
      4 6.02 21:06:31 INFO  BSP server:   targets = ArrayList (                                                                                    │21:06:35 │ metals:  28s (0%)               │
      3 6.02 21:06:31 INFO  BSP server:     BuildTargetIdentifier [                                                                                │21:06:35 │ metals:  14s (0%)               │
      2 6.02 21:06:31 INFO  BSP server:       uri = "file:/home/kristian/projects/shopping/.bleep/builds/bsp/.bloop/tests/?id=tests"               │21:06:35 │ metals:  2s (0%)                │
      1 6.02 21:06:31 INFO  BSP server:     ],                                                                                                     │21:06:35 │ metals:  4s (0%)                │
  10031 6.02 21:06:31 INFO  BSP server:     BuildTargetIdentifier [                                                                                │21:06:35 │ metals:  18s (0%)               │
      1 6.02 21:06:31 INFO  BSP server:       uri = "file:/home/kristian/projects/shopping/.bleep/builds/bsp/.bloop/shopping/?id=shopping"         │21:06:35 │ metals:  38s (0%)               │
      2 6.02 21:06:31 INFO  BSP server:     ]                                                                                                      │21:06:35 │ metals:  16s (0%)               │
      3 6.02 21:06:31 INFO  BSP server:   )                                                                                                        │21:06:35 │ metals:  24s (0%)               │
      4 6.02 21:06:31 INFO  BSP server: ] org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.                            │21:06:35 │ metals:  35s (0%)               │
      5 6.02 21:06:31 INFO  BSP server:   at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)                │21:06:35 │ metals:  28s (0%)               │
      6 6.02 21:06:31 INFO  BSP server:   at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)                              │21:06:35 │ metals:  26s (0%)               │
      7 6.02 21:06:31 INFO  BSP server:   at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)    │21:06:35 │ metals:  30s (0%)               │
      8 6.02 21:06:31 INFO  BSP server:   at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)            │21:06:35 │ metals:   (0%)                  │
      9 6.02 21:06:31 INFO  BSP server:   at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)    │21:06:35 │ metals: Importing build 38s (0%)│
     10 6.02 21:06:31 INFO  BSP server:   at java.base@17.0.6/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)              │21:06:35 │ metals:  23s (0%)               │
     11 6.02 21:06:31 INFO  BSP server:   at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)                             │21:06:35 │ metals:  25s (0%)               │
     12 6.02 21:06:31 INFO  BSP server:   at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)      │21:06:35 │ metals:  7s (0%)                │
     13 6.02 21:06:31 INFO  BSP server:   at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)      │21:06:35 │ metals:  23s (0%)               │
     14 6.02 21:06:31 INFO  BSP server:   at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)                                                │21:06:35 │ metals:  24s (0%)               │
     15 6.02 21:06:31 INFO  BSP server:   at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)               │21:06:35 │ metals:  32s (0%)               │
     16 6.02 21:06:31 INFO  BSP server:   at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:20│21:06:35 │ metals:  19s (0%)               │
     17 6.02 21:06:31 INFO  BSP server:
 ```
     
Now, I poked around some in the bsp and bleep source code and I could not figure out why this would cause an error. Everything looks right to me.

Relevant files 
bleep: https://github.com/oyvindberg/bleep/blob/6c93b316a64603750bed442ccb5b698bb47384df/bleep-core/src/scala/bleep/bsp/BleepBspServer.scala#L205

bsp:   [@JsonRequest("buildTarget/dependencyModules")](https://github.com/build-server-protocol/build-server-protocol/blob/31d5774f934f303e0068c58bc1fe7dd9a38b6f9c/bsp4j/src/ch/epfl/scala/bsp4j/BuildServer.java#L102)

Edit:
This is the source of the exception: https://github.com/eclipse-lsp4j/lsp4j/blob/f235e91fbe2e45f62e185bbb9f6d21bed48eb2b9/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler.java#L133

Maybe related to this:
https://github.com/VirtusLab/scala-cli/issues/2792
See: https://github.com/oyvindberg/bleep/blob/6c93b316a64603750bed442ccb5b698bb47384df/bleep-core/src/scala/bleep/bsp/BleepBspServer.scala#L74

**Comment by joan38** [comment]
I'm experiencing the same issue on my side from scala-cli with Metals
