### ISSUE TITLE
Keep getting `libdaemonjvm.server.LockError$ZombieFound` in Earthly satellite

### ISSUE THREAD

**Issue by nafg** [oyvindberg/bleep#397]
```
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36, trying again in 3 seconds
               +dist | Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36
               +dist | 	at bloop.Bloop$.loop$1(Bloop.scala:102)
               +dist | 	at bloop.Bloop$.main(Bloop.scala:114)
               +dist | 	at bloop.Bloop.main(Bloop.scala)
               +dist | Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 36
               +dist | 	at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
               +dist | 	at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
               +dist | 	at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
               +dist | 	at scala.Option.flatMap(Option.scala:[283](https://gitlab.com/bookphone/igud-bnei-torah/-/jobs/7445435560#L283))
               +dist | 	at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
               +dist | 	at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
               +dist | 	at bloop.Bloop$.loop$1(Bloop.scala:93)
               +dist | 	... 2 more
               +dist | Caused by: java.net.ConnectException: Connection refused
               +dist | 	at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
               +dist | 	at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:154)
               +dist | 	at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:150)
               +dist | 	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:878)
               +dist | 	at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
               +dist | 	at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
               +dist | 	at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
               +dist | 	at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
               +dist | 	at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
               +dist | 	... 8 more
```

**Comment by oyvindberg** [comment]
Interesting. What happens before this? And what is the platform?

It does look a problem outside of bleep, somewhere in bloop-rifle, bloop or libdaemonjvm. It may absolutely be bleep's fault, but I don't have any insight into this part of the start to be honest.
