### ISSUE TITLE
Possible issue with native image and --only for tests

### ISSUE THREAD

**Issue by KristianAN** [oyvindberg/bleep#411]
when trying to use the --only option for testing I get the following stacktrace

```shell
📕 command failed unexpectedly! This really shouldn't happen. Please report. java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
        at java.base@21.0.2/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base@21.0.2/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at bleep.commands.Test.runWithServer$$anonfun$1$$anonfun$1(Test.scala:46)
        at scala.util.Either.flatMap(Either.scala:360)
        at bleep.commands.Test.runWithServer$$anonfun$1(Test.scala:52)
        at scala.util.Either.flatMap(Either.scala:360)
        at bleep.commands.Test.runWithServer(Test.scala:53)
        at bleep.BleepCommandRemote.run(BleepCommandRemote.scala:100)
        at bleep.Main$.$anonfun$42$$anonfun$1$$anonfun$2(Main.scala:516)
        at bleep.Main$.run$$anonfun$1(Main.scala:585)
        at scala.util.Try$.apply(Try.scala:217)
        at bleep.Main$.run(Main.scala:585)
        at bleep.Main$.$anonfun$42$$anonfun$1(Main.scala:516)
        at bleep.logging.TypedLoggerResource$.bleep$logging$TypedLoggerResource$Ops$$anon$4$$_$use$$anonfun$4(TypedLoggerResource.scala:41)
        at bleep.logging.TypedLoggerResource$Ops$$anon$1.use$$anonfun$1(TypedLoggerResource.scala:20)
        at bleep.logging.TypedLoggerResource$.bleep$logging$TypedLoggerResource$Ops$$anon$3$$_$use$$anonfun$3$$anonfun$1(TypedLoggerResource.scala:34)
        at bleep.logging.TypedLoggerResource$$anon$6.use(TypedLoggerResource.scala:56)
        at bleep.logging.TypedLoggerResource$Ops$$anon$3.use$$anonfun$3(TypedLoggerResource.scala:34)
        at bleep.logging.TypedLoggerResource$Ops$$anon$1.use$$anonfun$1(TypedLoggerResource.scala:20)
        at bleep.logging.TypedLoggerResource$$anon$7.use(TypedLoggerResource.scala:67)
        at bleep.logging.TypedLoggerResource$Ops$$anon$1.use(TypedLoggerResource.scala:20)
        at bleep.logging.TypedLoggerResource$Ops$$anon$3.use(TypedLoggerResource.scala:36)
        at bleep.logging.TypedLoggerResource$Ops$$anon$1.use(TypedLoggerResource.scala:20)
        at bleep.logging.TypedLoggerResource$Ops$$anon$4.use(TypedLoggerResource.scala:41)
        at bleep.Main$.$anonfun$42(Main.scala:518)
        at bleep.ExitCode.andThen(ExitCode.scala:6)
        at bleep.Main$._main(Main.scala:520)
        at bleep.Main$.main(Main.scala:526)
        at bleep.Main.main(Main.scala)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base@21.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```
        
 This does not occur when running it as a jar.

**Comment by oyvindberg** [comment]
this is caused by missing entries here:
```
/Users/oyvind/bleep/bleep-cli/src/resources/META-INF/native-image/org.scala-lang/scala-lang/reflect-config.json
```

in #394 we made use of some bloop types we hadn't used before, and they need to be added here for bsp4j to work.
